name: geesereleif
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  google_fonts:
  path_provider:
  provider:
  font_awesome_flutter:
  shimmer:
  intl:
  flushbar: 1.10.0
  url_launcher:
  keyboard_visibility:
  maps_launcher:
  bubble:
  flutter_staggered_grid_view:
  photo_view:
  image_picker:
  image_cropper:
  cached_network_image:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/

module:
  androidX: true
